### ISSUE TITLE
Crashing on 1.21.x

### ISSUE THREAD

**Issue by anoomolu** [Infinidoge/simple-durability-tooltip#2]
Hiya! Been a long-time user of this mod on 1.20.1, does what it says on the tin :)

It seems to crash however, on 1.21 and 1.21.1. Made a test instance and here was the crashlog:

https://mclo.gs/Ypvi4Pw

**Comment by Infinidoge** [comment]
Damn, I thought I was safe adding those as supported versions as it was an unlikely part of the code to be changed. They switched to using `TooltipType` instead of `TooltipContext` for getting `isAdvanced`, which is causing the mixin to fail. It should be a pretty easy fix though, at least.

**Comment by Infinidoge** [comment]
Released a new jar that supports 1.21. I may eventually look into figuring out a unified all-version jar, but that's a later problem.
https://modrinth.com/mod/simple-durability-tooltip/version/v2.1.0
